/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return ``{"status": "ok"}`` once the app is serving.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a login challenge
         * @description Start the age challenge for a registered device.
         *
         *     The server encrypts a random nonce **to the device's public key** and returns
         *     it (base64) alongside a short-lived `challenge_token` that binds the device
         *     and the nonce. The device decrypts the challenge with its private key and
         *     answers via `/auth/verify`.
         */
        post: operations["challenge_auth_challenge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login, receive a session token
         * @description Submit the decrypted nonce to finish the challenge.
         *
         *     On success the server returns a bearer `access_token` to send as
         *     `Authorization: Bearer <token>` on subsequent calls.
         */
        post: operations["verify_auth_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Identify the current session
         * @description Return the device and account the bearer token authenticates.
         */
        get: operations["whoami_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Create an account from an email + password, returning a web session token.
         *
         *     Account creation lives on the web, not the CLI. An optional `recovery_pubkey`
         *     (minted in the browser) is stored as the account's recovery key; its private
         *     half never leaves the user.
         */
        post: operations["register_account_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in to an account
         * @description Exchange email + password for a web session token.
         */
        post: operations["login_accounts_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the current account
         * @description Return the caller's account, including its recovery public key.
         *
         *     Accepts either a web session or a device session, so the CLI can read the
         *     recovery key it must seal secrets to.
         */
        get: operations["me_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me/recovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the account's recovery key
         * @description Set the account's recovery public key (minted in the browser), once.
         *
         *     Registration can carry a recovery key already; this lets an account that
         *     signed up without one mint it later. It is write-once — a second attempt is
         *     refused (409) so secrets sealed to the existing key are never stranded.
         */
        put: operations["set_recovery_key_accounts_me_recovery_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push local changes
         * @description Upload a batch of changes for the caller's account.
         *
         *     Each item is created, updated against its `base_version`, or tombstoned.
         *     Optimistic concurrency is per item: a stale write comes back with
         *     `status: "conflict"` and the winning `version` (so the client can pull and
         *     reconcile) while the rest of the batch still applies. `recipients` sets which
         *     devices may pull the secret.
         */
        post: operations["push_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull changes since a cursor
         * @description Return the secrets this device may read with `seq > since`.
         *
         *     Results are ordered by `seq` and include tombstones (deleted secrets) so the
         *     deletion propagates. The response `cursor` is the new high-water mark to pass
         *     as `since` next time.
         */
        get: operations["changes_sync_changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enroll/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a client-generated pairing invite
         * @description Store an invite whose code was generated by the caller.
         *
         *     Callable by a logged-in **web session** or an already-linked **device**. The
         *     plaintext code never reaches the server — only its hash and the MAC'd roster,
         *     which the server relays to the joiner but cannot forge.
         */
        post: operations["create_invite_enroll_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enroll/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join an account with an invite code
         * @description Admit a new device into the invite's account, consuming the invite.
         *
         *     Unauthenticated — the code hash is the authorization. Returns the inviter's
         *     roster so the joiner can verify it under the code and adopt those devices as
         *     trust anchors. The device is active immediately; the inviter vouches for it
         *     (a signed cert) on its next sync.
         */
        post: operations["join_enroll_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enroll/invite/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll an invite for its join proof
         * @description Return the device that redeemed the caller's invite and its join MAC.
         *
         *     The inviter verifies the MAC under the code it minted — proving this exact
         *     device redeemed that code — and then publishes a vouch cert for it.
         */
        get: operations["invite_proof_enroll_invite__invite_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the account's devices
         * @description Return every device in the caller's account.
         */
        get: operations["list_devices_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a device by id
         * @description Return a single device by its id, within the caller's account.
         *
         *     A device belonging to another account is reported as 404, not disclosed.
         */
        get: operations["fetch_device_devices__device_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trust/certs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull trust certs since a cursor
         * @description Return the account's trust certs with `log_seq > since`, in order.
         *
         *     The client verifies every cert's signature and per-issuer chain, then
         *     recomputes which devices are trusted.
         */
        get: operations["changes_trust_certs_get"];
        put?: never;
        /**
         * Publish a signed trust cert
         * @description Append a vouch/revoke cert to the caller's account trust log.
         *
         *     The authenticated device may publish only its own certs (`issuer_id` must be
         *     this device), and its `seq` must be exactly one past its last published cert.
         *     The server stores the cert opaquely; it does not check the signature.
         */
        post: operations["publish_trust_certs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_stats_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/security": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security */
        get: operations["security_stats_security_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Recovery Pubkey
             * @description The account's recovery age public key, or null if none is set.
             */
            recovery_pubkey: string | null;
        };
        /** AccountSessionResponse */
        AccountSessionResponse: {
            /**
             * Access Token
             * @description Bearer token for the account (web) session.
             */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token lifetime in seconds.
             */
            expires_in: number;
        };
        /** ActivityPointResponse */
        ActivityPointResponse: {
            /**
             * Date
             * Format: date
             * @description UTC calendar date represented by this point.
             */
            date: string;
            /**
             * Created
             * @description Latest secret states first persisted on this UTC date.
             */
            created: number;
            /**
             * Updated
             * @description Latest non-deleted mutations on this UTC date.
             */
            updated: number;
            /**
             * Deleted
             * @description Latest tombstones persisted on this UTC date.
             */
            deleted: number;
        };
        /** ChallengeRequest */
        ChallengeRequest: {
            /**
             * Public Key
             * @description The device's age public key (age1…).
             */
            public_key: string;
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /**
             * Challenge
             * @description Base64 age ciphertext; decrypt with the device private key.
             */
            challenge: string;
            /**
             * Challenge Token
             * @description Opaque token binding this challenge; return it to verify.
             */
            challenge_token: string;
        };
        /** ChangedSecretResponse */
        ChangedSecretResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version */
            version: number;
            /**
             * Deleted
             * @description True for a tombstone (deleted secret).
             */
            deleted: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Seq
             * @description Sync sequence; pass the max back as the next cursor.
             */
            seq: number;
            /**
             * Ciphertext B64
             * @description Base64 opaque ciphertext.
             */
            ciphertext_b64: string;
        };
        /** ChangesResponse */
        ChangesResponse: {
            /** Secrets */
            secrets: components["schemas"]["ChangedSecretResponse"][];
            /**
             * Cursor
             * @description New high-water seq; pass as `since` on the next pull.
             */
            cursor: number;
        };
        /** CreateInviteRequest */
        CreateInviteRequest: {
            /**
             * Code Hash
             * @description Hex SHA-256 of the client-generated code.
             */
            code_hash: string;
            /**
             * Roster
             * @description Inviter's trusted devices, MAC'd under the code; empty for the web.
             */
            roster?: components["schemas"]["RosterEntry"][];
        };
        /** CreateInviteResponse */
        CreateInviteResponse: {
            /**
             * Invite Id
             * Format: uuid
             * @description Handle to poll for the join proof.
             */
            invite_id: string;
            /**
             * Expires At
             * Format: date-time
             * @description When the code stops being valid.
             */
            expires_at: string;
        };
        /** DeviceResponse */
        DeviceResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Device Name */
            device_name: string;
            /** Public Key */
            public_key: string;
            /**
             * Sign Public Key
             * @description Ed25519 signing public key (base64); verifies the device's trust certs.
             */
            sign_public_key: string;
            /**
             * Status
             * @description Trust lifecycle: pending | active | revoked.
             */
            status: string;
            /**
             * Last Seen At
             * @description Last authenticated call, if any.
             */
            last_seen_at: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteProofResponse */
        InviteProofResponse: {
            /**
             * Consumed
             * @description Whether a device has redeemed the invite.
             */
            consumed: boolean;
            /**
             * Join Mac
             * @description The redeeming device's join MAC, once consumed.
             */
            join_mac: string;
            /** @description The device that redeemed the invite, if any. */
            device?: components["schemas"]["DeviceResponse"] | null;
        };
        /** JoinRequest */
        JoinRequest: {
            /**
             * Code Hash
             * @description Hex SHA-256 of the pairing code the joiner holds.
             */
            code_hash: string;
            /**
             * Device Name
             * @description Human-readable name for the joining device.
             */
            device_name: string;
            /**
             * Public Key
             * @description The joining device's age public key (age1…).
             */
            public_key: string;
            /**
             * Sign Public Key
             * @description Its Ed25519 signing public key (base64).
             * @default
             */
            sign_public_key: string;
            /**
             * Join Mac
             * @description HMAC binding the joiner's keys to the code, for the inviter.
             * @default
             */
            join_mac: string;
        };
        /** JoinResponse */
        JoinResponse: {
            device: components["schemas"]["DeviceResponse"];
            /**
             * Roster
             * @description The inviter's trusted devices for the joiner to adopt as anchors.
             */
            roster: components["schemas"]["RosterEntry"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * @description Login email.
             */
            email: string;
            /**
             * Password
             * @description Account password.
             */
            password: string;
        };
        /** PushItemRequest */
        PushItemRequest: {
            /**
             * Id
             * Format: uuid
             * @description Client-generated secret id (stable across devices).
             */
            id: string;
            /**
             * Ciphertext B64
             * @description Base64 opaque ciphertext; may be empty only for a tombstone.
             * @default
             */
            ciphertext_b64: string;
            /**
             * Base Version
             * @description Server version the client edited (0 to create); guards concurrency.
             * @default 0
             */
            base_version: number;
            /**
             * Deleted
             * @description True to tombstone the secret.
             * @default false
             */
            deleted: boolean;
            /**
             * Recipients
             * @description age public keys the secret is sealed to (who may pull it).
             * @default []
             */
            recipients: string[];
        };
        /** PushRequest */
        PushRequest: {
            /** Items */
            items: components["schemas"]["PushItemRequest"][];
        };
        /** PushResponse */
        PushResponse: {
            /** Results */
            results: components["schemas"]["PushResultResponse"][];
        };
        /** PushResultResponse */
        PushResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @description "applied" or "conflict".
             */
            status: string;
            /**
             * Version
             * @description Resulting (or current, on conflict) server version.
             */
            version: number;
            /**
             * Seq
             * @description Resulting sync sequence (0 on conflict).
             */
            seq: number;
        };
        /** RegisterAccountRequest */
        RegisterAccountRequest: {
            /**
             * Email
             * @description Login email; the account's password identifier.
             */
            email: string;
            /**
             * Password
             * @description Account password (min 8 chars).
             */
            password: string;
            /**
             * Recovery Pubkey
             * @description Recovery age public key, minted in the browser. The private half is shown to the user once and never sent.
             */
            recovery_pubkey?: string | null;
        };
        /** RosterEntry */
        RosterEntry: {
            /**
             * Device Id
             * @description A trusted device's id.
             */
            device_id: string;
            /**
             * Enc Pub
             * @description Its age public key.
             */
            enc_pub: string;
            /**
             * Sign Pub
             * @description Its Ed25519 signing key.
             */
            sign_pub: string;
            /**
             * Mac
             * @description HMAC of the entry under the invite code.
             */
            mac: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /**
             * Access Token
             * @description Bearer token for Authorization headers.
             */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token lifetime in seconds.
             */
            expires_in: number;
        };
        /** SetRecoveryKeyRequest */
        SetRecoveryKeyRequest: {
            /**
             * Recovery Pubkey
             * @description Recovery age public key, minted in the browser. The private half is shown to the user once and never sent. Write-once per account.
             */
            recovery_pubkey: string;
        };
        /** StatsActivityResponse */
        StatsActivityResponse: {
            /** @description Time window represented by the activity points. */
            period: components["schemas"]["StatsPeriod"];
            /**
             * Points
             * @description Daily latest-mutation points in chronological order.
             */
            points: components["schemas"]["ActivityPointResponse"][];
        };
        /** StatsOverviewResponse */
        StatsOverviewResponse: {
            /**
             * Passwords
             * @description Client-provided password count; zero until available.
             */
            passwords: number;
            /**
             * Bank Cards
             * @description Client-provided card count; zero until available.
             */
            bank_cards: number;
            /**
             * Notes
             * @description Client-provided note count; zero until available.
             */
            notes: number;
            /**
             * Files
             * @description Client-provided file count; zero until available.
             */
            files: number;
            /**
             * Trusted Devices
             * @description Number of active trusted devices.
             */
            trusted_devices: number;
            /**
             * Revoked Devices
             * @description Number of revoked devices.
             */
            revoked_devices: number;
            /**
             * Pending Devices
             * @description Number of devices awaiting approval.
             */
            pending_devices: number;
        };
        /**
         * StatsPeriod
         * @description Supported time windows for dashboard activity.
         * @enum {string}
         */
        StatsPeriod: "7d" | "30d" | "90d";
        /** StatsSecurityResponse */
        StatsSecurityResponse: {
            /**
             * Status
             * @description Warning when revoked or pending devices exist; good otherwise.
             * @enum {string}
             */
            status: "good" | "warning";
            /**
             * Trusted Devices
             * @description Number of active trusted devices.
             */
            trusted_devices: number;
            /**
             * Revoked Devices
             * @description Number of revoked devices.
             */
            revoked_devices: number;
            /**
             * Pending Devices
             * @description Number of devices awaiting approval.
             */
            pending_devices: number;
            /**
             * Alerts
             * @description Persisted active security alerts; zero until implemented.
             */
            alerts: number;
            /**
             * Last Sync At
             * @description Latest successful account sync, or null until such events are persisted.
             */
            last_sync_at: string | null;
        };
        /** TrustCertBody */
        TrustCertBody: {
            /**
             * Kind
             * @description 'vouch' or 'revoke'.
             */
            kind: string;
            /**
             * Account Id
             * @description Account the cert belongs to.
             */
            account_id: string;
            /**
             * Issuer Id
             * @description Device id that signed the cert.
             */
            issuer_id: string;
            /**
             * Seq
             * @description Issuer's monotonic per-cert counter (contiguous).
             */
            seq: number;
            /**
             * Prev Hash
             * @description Chain link to the issuer's previous cert.
             * @default
             */
            prev_hash: string;
            /**
             * Subject Id
             * @description Vouch: the admitted device id.
             * @default
             */
            subject_id: string;
            /**
             * Subject Enc Pub
             * @description Vouch: the subject's age public key.
             * @default
             */
            subject_enc_pub: string;
            /**
             * Subject Sign Pub
             * @description Vouch: the subject's signing key.
             * @default
             */
            subject_sign_pub: string;
            /**
             * Target Id
             * @description Revoke: the removed device id.
             * @default
             */
            target_id: string;
            /**
             * Issued At
             * @description Unix seconds.
             */
            issued_at: number;
            /**
             * Sig
             * @description Base64 Ed25519 signature over the cert's canonical form.
             */
            sig: string;
        };
        /** TrustChangesResponse */
        TrustChangesResponse: {
            /** Certs */
            certs: components["schemas"]["TrustCertBody"][];
            /**
             * Cursor
             * @description New high-water log cursor to pass as `since` next time.
             */
            cursor: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            /**
             * Challenge Token
             * @description The token from /auth/challenge.
             */
            challenge_token: string;
            /**
             * Nonce
             * @description Base64 of the decrypted challenge nonce.
             */
            nonce: string;
        };
        /** WhoAmIResponse */
        WhoAmIResponse: {
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    challenge_auth_challenge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Unknown/revoked device, or a bad/expired token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_auth_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Unknown/revoked device, or a bad/expired token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoami_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmIResponse"];
                };
            };
            /** @description Unknown/revoked device, or a bad/expired token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_account_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSessionResponse"];
                };
            };
            /** @description This email is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_accounts_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSessionResponse"];
                };
            };
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_accounts_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_recovery_key_accounts_me_recovery_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRecoveryKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Missing, invalid, or expired web session token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This account already has a recovery key. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_sync_push_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changes_sync_changes_get: {
        parameters: {
            query?: {
                /** @description Highest seq already applied; 0 for a full pull */
                since?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangesResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invite_enroll_invite_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInviteResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_enroll_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinResponse"];
                };
            };
            /** @description Unknown, already-used, or expired invite code. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This public key is already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_proof_enroll_invite__invite_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteProofResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such invite on this account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_devices_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"][];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fetch_device_devices__device_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such device in the caller's account. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changes_trust_certs_get: {
        parameters: {
            query?: {
                /** @description Highest log cursor already seen; 0 for the full log */
                since?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustChangesResponse"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_trust_certs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrustCertBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrustCertBody"];
                };
            };
            /** @description Missing, invalid, or expired bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The cert's seq is not the next in the issuer's chain. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_stats_overview_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_stats_activity_get: {
        parameters: {
            query?: {
                period?: components["schemas"]["StatsPeriod"];
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    security_stats_security_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsSecurityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
