"""Enrollment endpoints — invite a device, join with a code, verify the join.

The inviter generates the code and uploads its hash + a MAC'd roster; the server
never sees the code. On join the server records the joiner's MAC so the inviter
can poll GET /enroll/invite/{id}, verify who redeemed its code, and vouch for it.
See docs/sync_design.md §11.
"""

import json
from uuid import UUID

from fastapi import APIRouter, Depends, status

from gophkeeper.api.deps import get_account_id, provide
from gophkeeper.api.schemas.device import DeviceResponse
from gophkeeper.api.schemas.enroll import (
    CreateInviteRequest,
    CreateInviteResponse,
    InviteProofResponse,
    JoinRequest,
    JoinResponse,
    RosterEntry,
)
from gophkeeper.services.enrollment_service import EnrollmentService

router = APIRouter(prefix="/enroll", tags=["enroll"])


@router.post(
    "/invite",
    response_model=CreateInviteResponse,
    summary="Register a client-generated pairing invite",
    responses={401: {"description": "Missing, invalid, or expired bearer token."}},
)
async def create_invite(
    body: CreateInviteRequest,
    account_id: UUID = Depends(get_account_id),
    service: EnrollmentService = Depends(provide(EnrollmentService)),
) -> CreateInviteResponse:
    """Store an invite whose code was generated by the caller.

    Callable by a logged-in **web session** or an already-linked **device**. The
    plaintext code never reaches the server — only its hash and the MAC'd roster,
    which the server relays to the joiner but cannot forge.
    """
    roster_json = json.dumps([e.model_dump() for e in body.roster])
    invite = await service.create_invite(
        account_id=account_id, code_hash=body.code_hash, roster_json=roster_json
    )
    return CreateInviteResponse(invite_id=invite.id, expires_at=invite.expires_at)


@router.post(
    "/join",
    response_model=JoinResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Join an account with an invite code",
    responses={
        400: {"description": "Unknown, already-used, or expired invite code."},
        409: {"description": "This public key is already registered."},
    },
)
async def join(
    body: JoinRequest,
    service: EnrollmentService = Depends(provide(EnrollmentService)),
) -> JoinResponse:
    """Admit a new device into the invite's account, consuming the invite.

    Unauthenticated — the code hash is the authorization. Returns the inviter's
    roster so the joiner can verify it under the code and adopt those devices as
    trust anchors. The device is active immediately; the inviter vouches for it
    (a signed cert) on its next sync.
    """
    device, roster_json = await service.join(
        code_hash=body.code_hash,
        device_name=body.device_name,
        public_key=body.public_key,
        sign_public_key=body.sign_public_key,
        join_mac=body.join_mac,
    )
    roster = [RosterEntry(**e) for e in json.loads(roster_json)]
    return JoinResponse(device=DeviceResponse.from_domain(device), roster=roster)


@router.get(
    "/invite/{invite_id}",
    response_model=InviteProofResponse,
    summary="Poll an invite for its join proof",
    responses={
        401: {"description": "Missing, invalid, or expired bearer token."},
        404: {"description": "No such invite on this account."},
    },
)
async def invite_proof(
    invite_id: UUID,
    account_id: UUID = Depends(get_account_id),
    service: EnrollmentService = Depends(provide(EnrollmentService)),
) -> InviteProofResponse:
    """Return the device that redeemed the caller's invite and its join MAC.

    The inviter verifies the MAC under the code it minted — proving this exact
    device redeemed that code — and then publishes a vouch cert for it.
    """
    invite, device = await service.join_proof(account_id=account_id, invite_id=invite_id)
    return InviteProofResponse(
        consumed=invite.consumed_at is not None,
        join_mac=invite.join_mac,
        device=DeviceResponse.from_domain(device) if device is not None else None,
    )
