[dev]
dynaconf_merge = true  # merge these values on top of [default]

[dev.database]
host = "postgres"
port = 5432
user = "postgres"
password = "docker"
name = "gophkeeper"

[dev.api]
trusted_hosts = ["localhost", "127.0.0.1"]

[dev.run_settings]
logging_level = "DEBUG"

[dev.server]
reload = true
