name: CI Backend
on:
  push:
    branches:
      - main
      - dev
    # paths:
    #   - .github/workflows/ci-backend.yaml
    #   - backend/**
  pull_request:
    branches:
      - main
      - dev
    # paths:
    #   - .github/workflows/ci-backend.yaml
    #   - backend/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:18.4-alpine@sha256:1b1689b20d16a014a3d195653381cf2caa75a41a92d93b255a9d6ea29fd353aa
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: gophkeeper
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d gophkeeper"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      
      - name: Set up uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          working-directory: "backend"
          version: "0.11.25"
          enable-cache: "true"
          # cache-python: "true" # Python installation may be also cached
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        working-directory: "backend"
        run: uv sync

      - name: Install dbmate
        run: |
          mkdir -p /tmp/dbmate-bin
          curl -fsSL -o /tmp/dbmate-bin/dbmate https://github.com/amacneil/dbmate/releases/download/v2.33.0/dbmate-linux-amd64

          echo "dfd4027141b6e4357158099bdfe6c02b286af70f8e49057937744cf80b38ea1c /tmp/dbmate-bin/dbmate" | sha256sum --check --status

          chmod +x /tmp/dbmate-bin/dbmate
          echo "/tmp/dbmate-bin" >> "$GITHUB_PATH"

      - name: Run db migrations
        working-directory: "backend"
        env:
          DATABASE_URL: "postgres://postgres:docker@127.0.0.1:5432/gophkeeper?sslmode=disable"
        run: dbmate up
      
      - name: Run integration tests
        working-directory: "backend"
        env:
          TEST_DATABASE_URL: "postgresql+asyncpg://postgres:docker@127.0.0.1:5432/gophkeeper?ssl=disable"
          # TEST_DATABASE_URL: "postgres://postgres:docker@127.0.0.1:5432/gophkeeper?sslmode=disable"
        run: uv run pytest

  build:
    name: Build container image
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Extract metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=staging,enable=${{ github.ref_name == 'dev' }}
      
      - name: Extract image name
        id: image-name
        run: |
          cat ${{ steps.meta.outputs.bake-file-tags }} |
          jq -r '.target."docker-metadata-action".args.DOCKER_META_IMAGES' | 
          sed -e 's/^/name=\0/' >> "$GITHUB_OUTPUT"

      - name: Build image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "{{defaultContext}}:backend"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/backend.tar
          push: false

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: artifact
        with:
          name: backend-image
          retention-days: 1
          path: ${{ runner.temp }}/backend.tar
