name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
concurrency:
  group: ci-frontend-${{ github.ref }}
  cancel-in-progress: true
jobs:
  frontend-lint:
    name: Run lint for frontend
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup NodeJS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run lint
        working-directory: frontend
        run: npm run lint

  frontend-build:
    name: Build frontend image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      image-name: ${{ steps.image-name.outputs.name }}
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Extract metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=staging,enable=${{ github.ref_name == 'dev' }}
      
      - name: Extract image name
        id: image-name
        run: |
          cat ${{ steps.meta.outputs.bake-file-tags }} |
          jq -r '.target."docker-metadata-action".args.DOCKER_META_IMAGES' | 
          sed -e 's/^/name=\0/' >> "$GITHUB_OUTPUT"

      - name: Build frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: "{{defaultContext}}:frontend"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/frontend.tar
          push: false

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        id: artifact
        with:
          name: frontend-image
          retention-days: 1
          path: ${{ runner.temp }}/frontend.tar
 
  frontend-publish:
    name: Publish frontend image
    runs-on: ubuntu-24.04
    if: ${{ github.ref_name == 'main' || github.ref_name == 'dev' }}
    permissions:
      packages: write
    needs: [ frontend-build, frontend-lint ]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          artifact-ids: ${{ needs.frontend-build.outputs.artifact-id }}
          path: ${{ runner.temp }}
      
      - name: Load image
        run: docker load --input ${{ runner.temp }}/frontend.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push -a ${{ needs.frontend-build.outputs.image-name }}
