name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  frontend-build:
    name: Build frontend image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
      image-name: ${{ steps.image-name.outputs.name }}
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Extract metadata
        uses: docker/metadata-action@v6
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-frontend
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref_name == 'main' }}
            type=raw,value=staging,enable=${{ github.ref_name == 'dev' }}
      
      - name: Extract image name
        id: image-name
        run: |
          # echo ${{ steps.meta.outputs.bake-file-tags }} | 
          # jq -r '.target."docker-metadata-action".args.DOCKER_META_IMAGES' | 
          # sed -e 's/^/name=\0/' >> "$GITHUB_OUTPUT"
          echo ${{ steps.meta.outputs.bake-file-tags }}

      - name: Build frontend image
        uses: docker/build-push-action@v7
        with:
          context: "{{defaultContext}}:frontend"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/frontend.tar
          push: false

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        id: artifact
        with:
          name: frontend-image
          path: ${{ runner.temp }}/frontend.tar
 
  frontend-publish:
    name: Publish frontend image
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    needs: frontend-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ needs.frontend-build.outputs.artifact-id }}
          path: ${{ runner.temp }}
      
      - name: Load image
        run: docker load --input ${{ runner.temp }}/frontend.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push -a ${{ needs.frontend-build.outputs.image-name }}
