name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  backend-unit-tests:
    name: Run unit tests for Python backend
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Uvicorn
        uses: astral-sh/setup-uv@v8.2.0
        with:
          working-directory: "backend"
          enable-cache: "true"
          # cache-python: "true" # Python installation may be also cached
          cache-dependency-glob: "backend/uv.lock"

      - name: Run unit tests
        working-directory: "backend"
        run: make test-unit
